# Build Stage
FROM node:14 AS builder

WORKDIR /app

COPY package.json yarn.lock ./
COPY .env ./

RUN yarn --frozen-lockfile
COPY . .
RUN yarn build

# Production Stage
FROM node:14-alpine

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY package.json yarn.lock ./

RUN yarn install --production --frozen-lockfile

EXPOSE 3000

CMD ["yarn", "start:prod"]